mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.dolores.**.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#缓存数据库   116.62.223.237 Michael494326901
redis:
  host: 101.33.208.213
  password: Michael494326901
  timeout: 5000
  database: 0
  port: 6379
  jedis:
    pool:
      max-active: 16
      max-wait: 5000
      max-idle: 8
      min-idle: 2