#Spring 配置
spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/infohub?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3  # 最小空闲连接数量
      maximum-pool-size: 10  # 连接池最大连接数，默认是10
      max-lifetime: 999999
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
server:
  port: 8080
  servlet:
    context-path: /

eureka:
  client:
    enabled: false

jwt:
  secret-key: 4226452948404D635166546A576E5A7234753777217A25432A462D4A614E6452
  expiration: 86400000
  refresh-token: 604800000

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.dolores.**.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #缓存数据库   116.62.223.237 Michael494326901
redis:
  host: 127.0.0.1
  password:
  timeout: 5000
  database: 0
  port: 6379
  jedis:
    pool:
      max-active: 16
      max-wait: 5000
      max-idle: 8
      min-idle: 2

  #图形验证码
captcha:
  # 页面 <参数设置> 可开启关闭 验证码校验
  # 验证码类型 math 数组计算 char 字符验证
  type: MATH
  # line 线段干扰 circle 圆圈干扰 shear 扭曲干扰
  category: CIRCLE
  # 数字验证码位数
  numberLength: 1
  # 字符验证码长度
  charLength: 4

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes:
  # 匹配链接
  urlPatterns: /system/*