spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          timeout: 10000
          uri: git@github.com:MichaelD494/InfoHub-Config.git
          defaultLabel: main
          cloneOnStart: true
          basedir: D:\InfoHub-Config


server:
  port: 7000

eureka:
  client:
    enabled: false
    serviceUrl:
      #Eureka 服务端的地址
      defaultZone: http://localhost:8761/eureka
